### ISSUE TITLE
Agent crashes on azure > 8.9.0

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#1201]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Our agent makes a series of utilization calls to determine which cloud provider you are on.  This is used to send legacy usage data.
It currently crashes on azure  because the AWS token call returns an XML error before attempting the subsequent AWS metadata call.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior
Agent functions on azure.

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
Start agent 8.9.0+ on azure.

## Additional context

The agent crashes with

```sh
_http_outgoing.js:524
throw new ERR_INVALID_CHAR('header content', name);
^

TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["X-aws-ec2-metadata-token"]
at ClientRequest.setHeader (_http_outgoing.js:533:3)
at new ClientRequest (_http_client.js:242:14)
at request (http.js:46:10)
at Object.get (http.js:50:15)
at Object.wrappedRequest [as get] (/app/node_modules/newrelic/lib/instrumentation/core/http.js:412:22)
at Object.request (/app/node_modules/newrelic/lib/utilization/common.js:74:20)
at getAuthToken (/app/node_modules/newrelic/lib/utilization/aws-info.js:49:12)
at respond (/app/node_modules/newrelic/lib/utilization/common.js:94:7)
at ConcatStream.&lt;anonymous&gt; (/app/node_modules/concat-stream/index.js:37:43)
at ConcatStream.emit (events.js:326:22) {
code: 'ERR_INVALID_CHAR'
```

Response when making AWS token request on azure:

![curlOutput](https://user-images.githubusercontent.com/1874937/169877438-59d517b4-ea1e-4b90-a639-1a12c702a539.png)

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by bizob2828** [comment]
I'm going to close this until we can get more information.  I tried reproducing with a virtual machine and k8s cluster(AKS) in azure and both fail on the auth token request which prevents the code from making the metadata request and avoiding the crash the customer reported
