### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by jegj** [newrelic/node-newrelic#1544]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
I am using NestJS interceptors to send some metrics to New relic. I using the function `startWebTransaction`  just like an example that I found on internet.

```js
@Injectable()
export class NewrelicInterceptor implements NestInterceptor {
  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    return newrelic.startWebTransaction(context.getHandler().name, function () {
      const transaction = newrelic.getTransaction();
      return next.handle().pipe(
          tap(() => transaction.end())
      );
    });
  }
}
```

but on my CI/CD pipeline my tests always fails becuase the following error:

```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From modules/myproj/specs/myproj.controller.spec.ts.
      at ConcatStream.Writable (../node_modules/newrelic/node_modules/readable-stream/lib/_stream_writable.js:230:22)
      at new ConcatStream (../node_modules/newrelic/node_modules/concat-stream/index.js:32:12)
      at ConcatStream (../node_modules/newrelic/node_modules/concat-stream/index.js:12:47)
      at ClientRequest.awsRequest (../node_modules/newrelic/lib/utilization/common.js:75:14)
/builds/myproj/node_modules/newrelic/node_modules/readable-stream/lib/_stream_writable.js:239
  var isDuplex = this instanceof Duplex;
                      ^
TypeError: Right-hand side of 'instanceof' is not callable
    at ConcatStream.Writable (/builds/myproj/node_modules/newrelic/node_modules/readable-stream/lib/_stream_writable.js:239:23)
    at new ConcatStream (/builds/myproj/node_modules/newrelic/node_modules/concat-stream/index.js:32:12)
    at ConcatStream (/builds/myproj/node_modules/newrelic/node_modules/concat-stream/index.js:12:47)
    at ClientRequest.awsRequest (/builds/myproj/node_modules/newrelic/lib/utilization/common.js:75:14)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:695:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at Socket.socketOnData (node:_http_client:536:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
````

I do not have this problem on my local environment

## Expected Behavior

Test should pass without problems on the ci/cd pipeline

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Node version: v18.13.0
newrelic: ^9.7.5

**Comment by mrickard** [comment]
@jegj If the example you're working from is https://github.com/matewilk/nestjs-test-app ...that support is still experimental. I'd suggest opening a ticket with New Relic Support: https://support.newrelic.com/

**Comment by jegj** [comment]
Thanks for the info. Wondering if there is a better example about using interceptors with new relic
