### ISSUE TITLE
Trying to use APM with aws lambda

### ISSUE THREAD

**Issue by altieres** [newrelic/node-newrelic#1554]
## Description

I want to have APM on my aws lambda, to inspect transactions and find bottlenecks.
Note: I successfully installed "Serverless function monitoring", but realized the collected data is not what I need.

## Expected Behavior

Collect data like my non-lambda worker process.

Having this error:

```
INIT_START Runtime Version: nodejs:16.v12	Runtime Version ARN: arn:aws:lambda:sa-east-1::runtime:734d712d91ebc245bd01c52ae85b4025a7885efd1b8c87c0ce49f3e47d2116a4
--
2023-03-20T13:43:42.008Z	undefined	ERROR	Uncaught Exception 	{     "errorType": "Runtime.ImportModuleError",     "errorMessage": "Error: Cannot find module './default'\nRequire stack:\n- /var/task/api.js\n- /var/runtime/index.mjs",     "stack": [         "Runtime.ImportModuleError: Error: Cannot find module './default'",         "Require stack:",         "- /var/task/api.js",         "- /var/runtime/index.mjs",         "    at _loadUserApp (file:///var/runtime/index.mjs:996:17)",         "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1031:21)",         "    at async start (file:///var/runtime/index.mjs:1194:23)",         "    at async file:///var/runtime/index.mjs:1200:1"     ] }
```

## Steps to Reproduce

Just add "newrelic" on package.json and import 'newrelic' on index.ts.

## Your Environment

Node version: 16.x
Serverless framework with esbuild plugin

**Comment by mrickard** [comment]
@altieres This behavior is related to using ECMAScript modules in Lambda with v2 aws-sdk. There's no support for `NODE_PATH` in ESM. AWS has helpfully patched that with the v3 aws-sdk, which is available for Node 18 runtimes. See https://github.com/newrelic/newrelic-lambda-layers#support-for-es-modules-nodejs

**Comment by altieres** [comment]
@mrickard I'm sorry for this newbie question.
I followed your recommendation, but I still only have the lambda infrastructure data. I didn't get the APM metrics.
Is there any example project or tutorial so I can get APM working on the lambda?

**Comment by mrickard** [comment]
@altieres Are you using one of the Lambda Layers? That bundles both the Node agent for instrumenting your function and the NR Lambda Extension for delivering telemetry to NR. (If you're using the layer-installed agent, you won't want to bundle an agent in your deployment package.)

In general, we have some documentation on this here: https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own/

I'm not offhand sure if the NR Lambda CLI supports Node 18 and ESM yet, so you may need to configure manually instead of using the Lambda CLI.

And there are some example configurations here: https://github.com/newrelic/newrelic-lambda-extension/tree/main/examples/sam/node

Having looked at that forum thread, I think it's misleading, depending on what's meant by "APM." The Node APM agent is exactly the same agent used in the Serverless Monitoring product. So you can indeed get it to work. NR1's UI for Serverless isn't bundled into APM, though--serverless functions have their own UI. You'll want to find your function in the Entity Explorer. 

If you're still having difficulty with those instructions, I'd recommend opening a ticket with Global Technical Support--they're well equipped to help people with configuration problems. See https://support.newrelic.com/

**Comment by altieres** [comment]
Just as a follow up, my setup is working now.

@mrickard pointed me on the right direction:
- Traces will not be visible on APM, but on Entity explorer
- The lambda layer contais all newrelic code necessary

My main problem was with serverless esbuild generated bundle. I had to mark mongodb as external to help instrumentation to work as needed.

Thanks!

---
![Captura de Tela 2023-03-21 às 16 32 27](https://user-images.githubusercontent.com/642302/227734509-ae459b3f-7bd9-4e99-8ff6-ad79a05de8f7.png)
---
<img width="1500" alt="Captura de Tela 2023-03-25 às 15 09 19" src="https://user-images.githubusercontent.com/642302/227734542-7fdc2ef1-6e25-4de4-95ce-08ce8a5448fc.png">

**Comment by lucasklaassen** [comment]
@altieres How did you end up getting transaction level data into newrelic? Are you using: https://github.com/newrelic/serverless-newrelic-lambda-layers or manually instrumentation?

**Comment by altieres** [comment]
> @altieres How did you end up getting transaction level data into newrelic? Are you using: https://github.com/newrelic/serverless-newrelic-lambda-layers or manually instrumentation?

Yes. I’m using this plugin. 
Do you need some help?

**Comment by lucasklaassen** [comment]
@altieres Yes! I'm unable to see any entity or APM data in NewRelic. I see data is coming in under `AwsLambdaInvocation` and `AwsLambdaInvocationError` which I've built custom dashboards on. It gives me innovations, duration, errors, etc but I have not ability to see any data within a Transaction/Trace view like you've shown above.

My serverless yaml config is the following:

```
plugins:
...
  - serverless-newrelic-lambda-layers

custom:
  newRelic:
    accountId: XXX
    apiKey: XXX
    stages:
      - production
```

**Comment by altieres** [comment]
My serverless.yml is almost like yours. I just don't have the key "stages".

I think that you are searching on the wrong place. It was hard to me to find it...

- First select one lambda (steps 1, 2, 3)
- Search for one specific invocation (steps 4, 5)
- An see the trace for this specific invocation (step 6)

What of this steps are you able to do?


<img width="981" alt="Captura de Tela 2023-07-11 às 17 03 59" src="https://github.com/newrelic/node-newrelic/assets/642302/d742ef72-e907-49f4-9d69-3287e7d4936a">

<img width="1605" alt="Captura de Tela 2023-07-11 às 17 09 54" src="https://github.com/newrelic/node-newrelic/assets/642302/63025031-5335-4c73-bcfd-1daddb9b29bd">

<img width="1637" alt="Captura de Tela 2023-07-11 às 17 11 24" src="https://github.com/newrelic/node-newrelic/assets/642302/aa810535-62f4-44d7-9965-9005ba6f3ac9">

**Comment by lucasklaassen** [comment]
My problem is that when I got to All Entities it doesn't allow me to search or filter for any data.
<img width="1792" alt="Screenshot 2023-07-11 at 6 29 21 PM" src="https://github.com/newrelic/node-newrelic/assets/6452107/e645ef6f-4425-4a21-8964-b90a3da78186">

**Comment by altieres** [comment]
Wow...
Be sure to use a "USER" license.

<img width="981" alt="Captura de Tela 2023-07-12 às 11 38 51" src="https://github.com/newrelic/node-newrelic/assets/642302/4c47f9c7-5667-49bd-b360-6775f1e4a4a4">

**Comment by jomiva** [comment]
> @altieres yes I am using a User License and data is successfully coming into the account as I can query it within the Query My Data section.
> 
> But entities is showing as blank.

Were you able to solve this?

**Comment by lucasklaassen** [comment]
@jomiva I ended up just building a dashboard based on custom queries from the data coming in. Wasn't able to figure out how to get it to show up in the APM.
