### ISSUE TITLE
v10 Newrelic causes issue with aws-s3 sdk in some cases

### ISSUE THREAD

**Issue by JoelV** [newrelic/node-newrelic#1604]
## Description

Upon upgrading to newrelic@10, and endpoint that where we make calls to aws using the aws-sdk gave the following error

```
message:Duplicate middleware name 'NewRelicHeader'
```
Trace
```
"Error: Duplicate middleware name 'NewRelicHeader'\n    at Object.add (/opt/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:130:31)\n    at Object.applyToStack (/opt/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:33:19)\n    at Object.use (/opt/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:167:20)\n    at S3Client.wrapShim (/opt/node_modules/@newrelic/aws-sdk/lib/v3/util.js:33:26)\n    at new WrappedClass (/opt/node_modules/newrelic/lib/shim/shim.js:2064:30)\n    at new S3Client (/opt/node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js:31:9)\n    at ProcessStatus.<anonymous> (/opt/app/helpers/s3-client.js:87:24)\n    at Generator.next (<anonymous>)\n    at /opt/app/helpers/s3-client.js:8:71\n    at new Promise (<anonymous>)"
```

## Expected Behavior

The above does not happen

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

```
message:Duplicate middleware name 'NewRelicHeader'
```
Trace
```
"Error: Duplicate middleware name 'NewRelicHeader'\n    at Object.add (/opt/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:130:31)\n    at Object.applyToStack (/opt/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:33:19)\n    at Object.use (/opt/node_modules/@aws-sdk/client-s3/node_modules/@aws-sdk/middleware-stack/dist-cjs/MiddlewareStack.js:167:20)\n    at S3Client.wrapShim (/opt/node_modules/@newrelic/aws-sdk/lib/v3/util.js:33:26)\n    at new WrappedClass (/opt/node_modules/newrelic/lib/shim/shim.js:2064:30)\n    at new S3Client (/opt/node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js:31:9)\n    at ProcessStatus.<anonymous> (/opt/app/helpers/s3-client.js:87:24)\n    at Generator.next (<anonymous>)\n    at /opt/app/helpers/s3-client.js:8:71\n    at new Promise (<anonymous>)"
```

## Steps to Reproduce
1. make endpoint with hapi that makes a call out to aws s3 to get presigned urls
2. make a call to the endpoint and it fails

## Your Environment

Node version: 17.3.0
Operating System and version: Alpine 3.1.3 Linux
Web Framework: Hapi

**Comment by bizob2828** [comment]
@JoelV sorry for your troubles. Can you create a reproduction case please? It'll make it easier for us to triage. I'm also going to move this to the node-newrelic-aws-sdk repository as that's where this instrumentation lives
