### ISSUE TITLE
Unhandled error during JSON.parse

### ISSUE THREAD

**Issue by OlenaHryshko** [newrelic/node-newrelic#1744]
## Description

Using newrelic to capture application logs + [pino](https://getpino.io/#/) as a logger agent.
While logging using pino, it is possible to pass [mergingObject](https://getpino.io/#/docs/api?id=mergingobject-object) to add more context to the log. In case key(s) of the metadata object contains `"` symbol, it is not getting shielded. So, logged object is not a JSON string, but newrelic lib tries to parse it to a JSON object.

NewRelic throws an error below:
```
SyntaxError:   Unexpected token s in JSON at position 219
at JSON.parse (<anonymous>)
at formatLogLine   (/app/node_modules/newrelic/lib/instrumentation/pino/pino.js:128:31)
at /app/node_modules/newrelic/lib/aggregators/log-aggregator.js:46:16
at Array.map (<anonymous>)
at LogAggregator._toPayloadSync   (/app/node_modules/newrelic/lib/aggregators/log-aggregator.js:44:32)
at LogAggregator.send   (/app/node_modules/newrelic/lib/aggregators/base-aggregator.js:105:32)
at /app/node_modules/newrelic/lib/agent.js:396:18
at new Promise (<anonymous>)
at Agent.forceHarvestAll   (/app/node_modules/newrelic/lib/agent.js:392:29)
at Timeout.afterTimeout [as _onTimeout]   (/app/node_modules/newrelic/lib/agent.js:514:11)
```

## Expected Behavior

Handle JSON.parse error.
In case it is not possible to parse JSON object from log string, save the whole log string as a message.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

As per comment in the code, newrelic calls pino asJson method. It returns invalid JSON string, which is getting passed into newrelic reformatLogLine method.
![image](https://github.com/newrelic/node-newrelic/assets/76039652/b9744017-34b3-4b83-b78c-c0e6d4f816ae)
![image](https://github.com/newrelic/node-newrelic/assets/76039652/afff0802-650b-4d32-b8c6-534af193cc28)

## Steps to Reproduce

1. Setup newrelic and enable logging.
2. Setup pino.
3. [Get instance](https://getpino.io/#/docs/api?id=logger-instance) of pino logger and call `logger.info({'some"prop': {'details': true}})`.
Code snippet:
```
const pino = require('pino');
const logger = pino();

logger.info({'some"prop': {'details': true}});
```
This will result in the log below:
`{"level":30,"time":1690897379299,"pid":41644,"hostname":"your-hostname","some"prop":{"details":true}}`
After this newrelic will pick up the log, try to do JSON.parse and throw the error mentioned above.

## Your Environment

* Node version: 16.16.0
* pino package version: 7.11.0
* newrelic package version: 9.14.1 (checked latest one 10.6.0 - same code algorithm)

**Comment by bizob2828** [comment]
@OlenaHryshko thanks for your report.  We can provide some defensive code but this also appears to be a bug with pino because it cannot properly stringify an object that has a `"` in a key.  Since pino manually builds serialization/de-serialization. If you do this in Node.js it just works

```
> JSON.stringify({ 'test"me': 'value'})
'{"test\\"me":"value"}'
> const a = JSON.stringify({ 'test"me': 'value'})
undefined
> JSON.parse(a)
{ 'test"me': 'value' }
>
```

**Comment by bizob2828** [comment]
@OlenaHryshko that has been released in [10.6.2](https://github.com/newrelic/node-newrelic/releases/tag/v10.6.2)

**Comment by OlenaHryshko** [comment]
@bizob2828 thank you for the notification
