### ISSUE TITLE
NetworkingError: Invalid character in header content [\"x-amz-copy-source\"]

### ISSUE THREAD

**Issue by Jm-47** [newrelic/node-newrelic#1796]
## Error in lambda instrumentation

Since the migration to node_modules/newrelic 11.1.0, the execution of a lambda fails because of newrelic instrumentation.

## Expected Behavior

Instrumentation should not affect the lambda execution, let alone throw an Error.

## Steps to Reproduce

This lambda makes use of AWS S3 copyObject command. There was no issue with older versions of the library.

Stack trace:
"NetworkingError [NetworkingError]: Invalid character in header content [\"x-amz-copy-source\"]
    at ClientRequest.setHeader (node:_http_outgoing:647:3)
    at new ClientRequest (node:_http_client:284:14)
    at Object.request (node:https:357:10)
    at makeRequest (/var/task/node_modules/newrelic/lib/instrumentation/core/http.js:410:22)
    at applySegment (/var/task/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:218:19)
    at instrumentRequest (/var/task/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:149:19)
    at LegacyContextManager.runInContext (/var/task/node_modules/newrelic/lib/context-manager/legacy-context-manager.js:59:23)
    at wrapped (/var/task/node_modules/newrelic/lib/transaction/tracer/index.js:203:37)
    at Tracer.addSegment (/var/task/node_modules/newrelic/lib/transaction/tracer/index.js:90:48)
    at instrumentOutbound (/var/task/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:117:23)"

## Your Environment

* Node version: 16

**Comment by Jm-47** [comment]
Possibly a mis-usage of aws api
