### ISSUE TITLE
Internal newrelic axios sometimes throw a 401 crashing the server

### ISSUE THREAD

**Issue by philippeauriach** [newrelic/node-newrelic#1829]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

We are using newrelic on our heroku app (nodejs).
We import it as recommanded, in the beginning of our index file : 
```
if (process.env.NODE_ENV !== 'development') {
  require('newrelic')
}
```

It works most of the time, but for some reason, some times, we get the following crash:
```
2023-10-24T09:06:26.715461+00:00 app[web.1]: AxiosError: Request failed with status code 401
2023-10-24T09:06:26.715472+00:00 app[web.1]: at settle (/app/node_modules/axios/dist/node/axios.cjs:1268:12)
2023-10-24T09:06:26.715473+00:00 app[web.1]: at IncomingMessage.handleStreamEnd (/app/node_modules/axios/dist/node/axios.cjs:2446:11)
2023-10-24T09:06:26.715475+00:00 app[web.1]: at IncomingMessage.emit (node:events:525:35)
2023-10-24T09:06:26.715475+00:00 app[web.1]: at IncomingMessage.emit (node:domain:552:15)
2023-10-24T09:06:26.715475+00:00 app[web.1]: at AsyncLocalStorage.run (node:async_hooks:319:14)
2023-10-24T09:06:26.715476+00:00 app[web.1]: at AsyncLocalContextManager.runInContext (/app/node_modules/newrelic/lib/context-manager/async-local-context-manager.js:62:38)
2023-10-24T09:06:26.715488+00:00 app[web.1]: at IncomingMessage.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:203:37)
2023-10-24T09:06:26.715490+00:00 app[web.1]: at IncomingMessage.wrappedResponseEmit (/app/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:313:24)
2023-10-24T09:06:26.715490+00:00 app[web.1]: at endReadableNT (node:internal/streams/readable:1359:12)
2023-10-24T09:06:26.715490+00:00 app[web.1]: at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-10-24T09:06:26.932143+00:00 heroku[web.1]: Process exited with status 1
2023-10-24T09:06:26.952610+00:00 heroku[web.1]: State changed from up to crashed
```

Which makes our server crash as the error is unhandled. What could be the cause of those sporadic 401 ? Any way to catch them?

## Expected Behavior
Do not crash - or at least allow us to handle those errors ?

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Node 18.12
* newrelic 11.3.0
* Heroku

**Comment by philippeauriach** [comment]
Sorry, it was on our end on something else
