### ISSUE TITLE
Unhandled rejections are not shown if using newrelic + winston logger

### ISSUE THREAD

**Issue by alexey-yarmosh** [newrelic/node-newrelic#2008]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Adding those lines makes app hide unhandled rejections. App just exits nothing related is shown in console:

```js
// index.js

import winston from 'winston';
const logger = winston.createLogger();

throw new Error('this error not shown');
```

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior
```
...
{"v":0,"level":30,"name":"newrelic","hostname":"MacBook-Pro-Alex.local","pid":54444,"time":"2024-02-09T16:12:19.342Z","msg":"Using New Relic for Node.js. Agent version: 11.10.3; Node version: v20.11.0."}
{"v":0,"level":40,"name":"newrelic","hostname":"MacBook-Pro-Alex.local","pid":54444,"time":"2024-02-09T16:12:19.342Z","msg":"New Relic for Node.js in worker_threads is not officially supported. Not starting! To bypass this, set `config.worker_threads.enabled` to true in configuration."}
file:///Users/baderfall/Documents/web/testing/nr-winston-demo/index.js:5
throw new Error('this error not shown');
      ^

Error: this error not shown
    at file:///Users/baderfall/Documents/web/testing/nr-winston-demo/index.js:5:7
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.11.0
```
[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
https://github.com/alexey-yarmosh/nr-winston-demo

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

Node version: v20.11.0
Operating System and version: MacOS 14.3

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by bizob2828** [comment]
@alexey-yarmosh sorry the troubles. I was able to trace it down. Our [instrumentation](https://github.com/newrelic/node-newrelic/blob/main/lib/instrumentation/nr-winston-transport.js#L22) sets handleExceptions to true which means these get forwarded to new relic logs feature.  This is behaving as designed, I need to ask around to other languages. Are you asking to actually see these and not have winston log and forward these to New Relic logs?

**Comment by alexey-yarmosh** [comment]
Indeed error is shown in New Relic logs. But all other logs are shown both there and in stdout. So to me, expected behaviour would be to see unhandled exception in stdout as well.

**Comment by bizob2828** [comment]
Yea let me dig. I'm not sure we can have both meaning it'll enqueue uncaught exceptions to New Relic logs and see it in stdout

**Comment by amychisholm03** [comment]
Hi @alexey-yarmosh, since your initial request, we have refactored our `winston` instrumentation to a subscriber-based model. As part of that work, the New Relic transport we add for log forwarding no longer enables winston's `handleExceptions` on loggers that have no transports of their own, which was what previously suppressed the uncaught error from the console. So, in your scenario, the error now propagates to Node and prints as expected. I ran the following code with 14.1.0 of the agent:
```
// index.mjs
import winston from 'winston'

// Give the agent a second to finish loading and wire up winston instrumentation.
setTimeout(() => {
  // eslint-disable-next-line no-unused-vars
  const logger = winston.createLogger()

  throw new Error('this error should be shown in the console')
}, 1000)

```

and the error is shown in the console as expected:
```
npm run start

> winston-uncaught-exception-repro@1.0.0 start
> node --env-file=.env --import newrelic index.mjs

{"v":0,"level":30,"name":"newrelic","hostname":"H94W9VYKK2","pid":92562,"time":"2026-06-22T22:25:51.230Z","msg":"Using New Relic for Node.js. Agent version: 14.1.0; Node version: v24.13.1."}
// other newrelic logs
{"v":0,"level":30,"name":"newrelic","hostname":"H94W9VYKK2","pid":92562,"time":"2026-06-22T22:25:52.168Z","msg":"Valid event_harvest_config received. Updating harvest cycles. {\"report_period_ms\":5000,\"harvest_limits\":{\"error_event_data\":8,\"log_event_data\":833,\"analytic_event_data\":833,\"custom_event_data\":250}}"}
{"v":0,"level":30,"name":"newrelic","hostname":"H94W9VYKK2","pid":92562,"time":"2026-06-22T22:25:52.177Z","msg":"Agent state changed from connected to started."}
file:///Users/achisholm/Desktop/newrelic-node-examples/application-logging/winston-uncaught-exception/index.mjs:25
  throw new Error('this error should be shown in the console')
  ^

Error: this error should be shown in the console
    at Timeout._onTimeout (file:///Users/achisholm/Desktop/newrelic-node-examples/application-logging/winston-uncaught-exception/index.mjs:25:9)
    at listOnTimeout (node:internal/timers:605:17)
    at process.processTimers (node:internal/timers:541:7)

Node.js v24.13.1
```

Please let me know if upgrading to the latest version of the agent solves your issue.

**Comment by amychisholm03** [comment]
Please re-open the issue if upgrading to the latest version of the agent doesn't solve your issue. The described bug is no longer reproducible in latest version of agent, 14.1.1.
