### ISSUE TITLE
Failed to instrument module @redis/client

### ISSUE THREAD

**Issue by MartinKolarik** [newrelic/node-newrelic#2012]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

When starting the app, I get the following warning:
```
{
"msg": "Failed to instrument module client using [...]\\node_modules\\newrelic\\lib\\instrumentation\\@redis\\client.js",
"component": "shimmer",
"stack": "TypeError: Cannot read properties of null (reading 'default')\n
    at initialize ([...]\\node_modules\\newrelic\\lib\\instrumentation\\@node-redis\\client.js:12:75)
    at _firstPartyInstrumentation ([...]\\node_modules\\newrelic\\lib\\shimmer.js:698:29)
    at loadInstrumentation ([...]\\node_modules\\newrelic\\lib\\shimmer.js:662:25)
    at [...]\\node_modules\\newrelic\\lib\\shimmer.js:573:14
    at Array.forEach (<anonymous>)
    at instrumentPostLoad ([...]\\node_modules\\newrelic\\lib\\shimmer.js:538:20)
    at _postLoad ([...]\\node_modules\\newrelic\\lib\\shimmer.js:722
:12)
    at onHook ([...]\\node_modules\\newrelic\\lib\\shimmer.js:366:14)
    at Hook._require.Module.require ([...]\\node_modules\\require-in-the-middle\\index.js:262:28)
    at require (node:internal/modules/helpers:130:18)",
"message": "Cannot read properties of null (reading 'default')"
}
```

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

The module is instrumented without errors.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

After a quick look at the [relevant code](https://github.com/newrelic/node-newrelic/blob/b460c7be589dd6fa801285b756bf66f62e0f10aa/lib/instrumentation/%40node-redis/client.js#L12), I see there's an attempt to load `dist/lib/client/commands.js` from `@redis/client,` but the shim object that does the loading has `_moduleRoot` set to `node_modules/@redis` (without `/client`) for some reason, so this fails:

![image](https://github.com/newrelic/node-newrelic/assets/6192491/ab3730bb-95b1-45bf-9c51-b012bee532cf)

I tried changing [the require call](https://github.com/newrelic/node-newrelic/blob/b460c7be589dd6fa801285b756bf66f62e0f10aa/lib/instrumentation/%40node-redis/client.js#L12) from `shim.require('dist/lib/client/commands.js')` to `shim.require('client/dist/lib/client/commands.js')`
and that fixes the issue - but not sure, it seems the real issue is the wrong shimmer root.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Redis: 4.6.13
* Newrelic: 11.10.3
* Node version: v20.8.1
* Operating System and version: Windows 11

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by jsumners-nr** [comment]
👋 thank you for the report. Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). Doing so will help us diagnose the issue. It should be the bare minimum code needed to trigger the issue, and easily runnable without any changes or extra code.

You may use a GitHub repository to host the code if it is too much to fit into a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) (or two).

**Comment by bizob2828** [comment]
@MartinKolarik thanks! I can reproduce your issue on windows.  We will investigate a fix and get back to you, sorry for your troubles.

**Comment by bizob2828** [comment]
Triage notes:

It looks like our [logic](https://github.com/newrelic/node-newrelic/blob/main/lib/shim/shim.js#L54) to determine the `_moduleRoot` for a shim instance is flawed on windows.

On unix:
```sh
{"v":0,"level":20,"name":"newrelic","hostname":"TK46XHNX04","pid":96221,"time":"2024-02-12T17:14:55.183Z","msg":"BOB DEBUG /Users/revans/code/redis-app/node_modules/@redis/client, dist/lib/client/commands.js","component":"Shim"}
```

On windows:
```sh
{"v":0,"level":20,"name":"newrelic","hostname":"node-test-vm","pid":7192,"time":"2024-02-12T17:12:50.899Z","msg":"BOB-DEBUG C:\\Users\\node_admin\\test\\node_modules\\@redis dist/lib/client/commands.js","component":"Shim"}
```

**Comment by bizob2828** [comment]
@MartinKolarik this was released yesterday in 11.10.4, can you verify this fixes your issue?
