### ISSUE TITLE
isBuiltin is not a function in node-newrelic 11.14.0 on Linux NodeJS 16.13.1

### ISSUE THREAD

**Issue by quynhduongphl** [newrelic/node-newrelic#2095]
newrelic throws error `isBuiltin is not a function` as part of the bootstrap sequence

## Description

Newrelic fails to bootstrap in v11.14.0 on Node16 Linux

## Expected Behavior

Newrelic bootstraps correctly

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

```
2024-03-21T03:18:43.061325244Z   _____
2024-03-21T03:18:43.061353444Z   /  _  \ __________ _________   ____
2024-03-21T03:18:43.061358444Z  /  /_\  \___   /  |  \_  __ \_/ __ \
2024-03-21T03:18:43.061362144Z /    |    \/    /|  |  /|  | \/\  ___/
2024-03-21T03:18:43.061365544Z \____|__  /_____ \____/ |__|    \___  >
2024-03-21T03:18:43.061369044Z         \/      \/                  \/
2024-03-21T03:18:43.061372545Z A P P   S E R V I C E   O N   L I N U X
2024-03-21T03:18:43.061375745Z
2024-03-21T03:18:43.061379545Z Documentation: http://aka.ms/webapp-linux
2024-03-21T03:18:43.061381945Z NodeJS quickstart: https://aka.ms/node-qs
2024-03-21T03:18:43.061384145Z NodeJS Version : v16.13.1
2024-03-21T03:18:43.061386245Z Note: Any data outside '/home' is not persisted
2024-03-21T03:18:43.061388345Z
2024-03-21T03:18:43.110309488Z Starting periodic command scheduler: cron.
2024-03-21T03:18:43.114546335Z Cound not find build manifest file at '/home/site/wwwroot/oryx-manifest.toml'
2024-03-21T03:18:43.114735637Z Could not find operation ID in manifest. Generating an operation id...
2024-03-21T03:18:43.114744437Z Build Operation ID: c9451c9b
2024-03-21T03:18:43.434722590Z Environment Variables for Application Insight's IPA Codeless Configuration exists..
2024-03-21T03:18:43.637209639Z Writing output script to '/opt/startup/startup.sh'
2024-03-21T03:18:43.852000324Z Running #!/bin/sh
2024-03-21T03:18:43.852035024Z
2024-03-21T03:18:43.852040925Z # Enter the source directory to make sure the script runs where the user expects
2024-03-21T03:18:43.852045725Z cd "/home/site/wwwroot"
2024-03-21T03:18:43.852050225Z
2024-03-21T03:18:43.852054225Z export NODE_PATH=/usr/local/lib/node_modules:$NODE_PATH
2024-03-21T03:18:43.852058925Z if [ -z "$PORT" ]; then
2024-03-21T03:18:43.852063225Z 		export PORT=8080
2024-03-21T03:18:43.852067425Z fi
2024-03-21T03:18:43.852070725Z
2024-03-21T03:18:43.852074425Z PATH="$PATH:/home/site/wwwroot" node src/start.js
2024-03-21T03:18:48.016624622Z New Relic for Node.js was unable to bootstrap itself due to an error:
2024-03-21T03:18:48.017575221Z TypeError: isBuiltin is not a function
2024-03-21T03:18:48.017606021Z     at new Shim (/home/site/wwwroot/node_modules/newrelic/lib/shim/shim.js:51:22)
2024-03-21T03:18:48.017612221Z     at Object.registerCoreInstrumentation (/home/site/wwwroot/node_modules/newrelic/lib/shimmer.js:327:24)
2024-03-21T03:18:48.017616921Z     at Object.bootstrapInstrumentation (/home/site/wwwroot/node_modules/newrelic/lib/shimmer.js:388:13)
2024-03-21T03:18:48.017622021Z     at createAgent (/home/site/wwwroot/node_modules/newrelic/index.js:164:11)
2024-03-21T03:18:48.017639221Z     at initialize (/home/site/wwwroot/node_modules/newrelic/index.js:105:15)
2024-03-21T03:18:48.017643921Z     at Object.<anonymous> (/home/site/wwwroot/node_modules/newrelic/index.js:39:3)
2024-03-21T03:18:48.017648721Z     at Module._compile (node:internal/modules/cjs/loader:1101:14)
2024-03-21T03:18:48.017652721Z     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
2024-03-21T03:18:48.017656621Z     at Module.load (node:internal/modules/cjs/loader:981:32)
2024-03-21T03:18:48.017660521Z     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

## Steps to Reproduce

Include v11.14.0 in package.json

## Your Environment

Node version: 16.13.1
Operating System and version: Linux 664c6502310e 5.15.138.1-4.cm2 #1 SMP Thu Nov 30 21:48:10 UTC 2023 x86_64 GNU/Linux

## Additional context

Downgrade to 11.5.0 solved this issue

**Comment by premjangir34** [comment]
+1

**Comment by quynhduongphl** [comment]
Well if this component will not work with node lower than v16.17.0 then maybe that needs to be put into `package.json` with a big fat error when doing `npm install` then? That would help people know that this library will blow up if running old version of Node16.
Quote `package.json` file:
`  "engines": {
    "node": ">=16",
    "npm": ">=6.0.0"
  },`

**Comment by tomasvalentaopenbean** [comment]
The minimum supported Node version should also be mentioned in the documentation.

**Comment by jsumners-nr** [comment]
Thank you for the feedback. The `engines` section in the `package.json` would not prevent the issue, as no package manager treats it as a breaking error. Additionally, Node.js LTS only covers the most recent release in LTS series of releases. For Node.js v16, that means 16.20.2 as of this post (see https://github.com/nodejs/Release#readme).

Also, be aware that Node.js v16 has been marked End-of-Life. The next major version of `newrelic` will drop support for it.

I am closing this issue as answered.

**Comment by wilkinsonj** [comment]
I see the same issue using Node 17.9.1

**Comment by jsumners-nr** [comment]
Odd numbered major releases of Node.js are not supported. They are intended to be feature preview releases by the Node.js team. Please review https://github.com/nodejs/Release#release-phases
