### ISSUE TITLE
MessageSpec undefined (error)

### ISSUE THREAD

**Issue by 0xRapid** [newrelic/node-newrelic#2097]
## Description

When adding an item to a queue using AWS SQS node package, it throws and error and doesn't pass the request through..

The SQS code is:
```
 const params: SendMessageParams = {
        MessageBody:  '{"tokenAddress":"0xe6d9f3fea5e20b1ec60ce3107beb1413a8e740b8","networkId":42161}',
        QueueUrl: this.url, //queue URL in AWS
        MessageDeduplicationId: uuidv4(), // random GUID
        MessageGroupId: '1', // Static
      };

      const response = await this.client.send(new SendMessageCommand(params));
```

The error:
```
TypeError: Cannot read properties of undefined (reading 'MessageSpec')
    at getSqsSpec (/usr/src/app/node_modules/.pnpm/@newrelic+aws-sdk@7.3.0/node_modules/@newrelic/aws-sdk/lib/v3/sqs.js:45:25)
    at recordProd (/usr/src/app/node_modules/.pnpm/newrelic@11.6.0/node_modules/newrelic/lib/shim/message-shim.js:289:33)
    at wrapper (/usr/src/app/node_modules/.pnpm/newrelic@11.6.0/node_modules/newrelic/lib/shim/shim.js:852:33)
    at SQSClient.send (/usr/src/app/node_modules/.pnpm/@smithy+smithy-client@2.5.0/node_modules/@smithy/smithy-client/dist-cjs/index.js:122:14)
    at SQSClient.wrappedSend (/usr/src/app/node_modules/.pnpm/@newrelic+aws-sdk@7.3.0/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:63:17)
    at SQSWrapper.<anonymous> (webpack:///libs/shared/utils/aws/src/lib/aws-sqs.ts:79:42)
    at Generator.next (<anonymous>)
    at /usr/src/app/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/src/app/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:165:16)
    at SQSWrapper.sendMessage (/usr/src/app/dist/apps/project/api/main.js:820:101055)
    at Object.<anonymous> (webpack:///libs/project/services/src/lib/holders-sqs.ts:29:35)
    at Generator.next (<anonymous>)
    at /usr/src/app/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/src/app/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:165:16) 
```

## Expected Behavior
Throw an error without crashing the actual request... the request is not being sent because of newrelic, that is pretty outrageous I have to say.

## Your Environment
Dependencies:
```
"@types/uuid": "8.3.4",
"@aws-sdk/client-sqs": "3.433.0"
"newrelic": "11.6.0",
```

* ex: Node version: 18.17.0
* ex: Operating System and version: alpine

**Comment by jsumners-nr** [comment]
👋 from the stack trace provided, it looks like you have `@newrelic/aws-sdk` version 7.3.0 installed:

> at SQSClient.wrappedSend (/usr/src/app/node_modules/.pnpm/@newrelic+aws-sdk@7.3.0/node_modules/@newrelic/aws-sdk/lib/v3/smithy-client.js:63:17)

That version of the `aws-sdk` package requires at least [version 11.11.0](https://github.com/newrelic/node-newrelic/releases/tag/v11.11.0) of the `newrelic` package. Please try upgrading your `newrelic` package.

**Comment by 0xRapid** [comment]
Yes, I upgraded to 11.14 which seems to solve it. I'm still looking to see if it happens.
