### ISSUE TITLE
Typescript ts-node does not support --experimental-loader or --loader, therefore never newrelic unable to run

### ISSUE THREAD

**Issue by alilland** [newrelic/node-newrelic#2110]
I am attempting to install newrelic on an express-API written in typescript, I am running node@20 right now, when I attempted to configure newrelic as i have done in the past (create a newrelic.js file and put newrelic at the top of the load order in the root of the app, with an express module config), in the past i have used  node@16, But now in node@20 i kept getting an error that `newrelic.instrumentLoadedModule` function was not found. 

```javascript
// top of the file
import newrelic from 'newrelic'
import express from 'express'
newrelic.instrumentLoadedModule(
  'express',
  express 
)

// rest of the express index.ts
```

```
$ NODE_ENV=${NODE_ENV:-development} nodemon -r tsconfig-paths/register -r newrelic ./src/index.ts

[nodemon] 3.1.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node -r tsconfig-paths/register -r newrelic ./src/index.ts`
/Users/aronlilland/Documents/dev/steppingStonesInternational/pathway-api/src/index.ts:10
newrelic.instrumentLoadedModule(
         ^
TypeError: newrelic_1.default.instrumentLoadedModule is not a function
    at Object.<anonymous> (/Users/aronlilland/Documents/dev/steppingStonesInternational/pathway-api/src/index.ts:10:10)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module.m._compile (/Users/aronlilland/Documents/dev/steppingStonesInternational/pathway-api/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/aronlilland/Documents/dev/steppingStonesInternational/pathway-api/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at phase4 (/Users/aronlilland/Documents/dev/steppingStonesInternational/pathway-api/node_modules/ts-node/src/bin.ts:649:14)
    at bootstrap (/Users/aronlilland/Documents/dev/steppingStonesInternational/pathway-api/node_modules/ts-node/src/bin.ts:95:10)
    at main (/Users/aronlilland/Documents/dev/steppingStonesInternational/pathway-api/node_modules/ts-node/src/bin.ts:55:10)
    at Object.<anonymous> (/Users/aronlilland/Documents/dev/steppingStonesInternational/pathway-api/node_modules/ts-node/src/bin.ts:800:3)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49
[nodemon] app crashed - waiting for file changes before starting...
^Cmake: *** [dev] Error 1
```

After delving in deeper to the newrelic docs and looking at the example from the ["Setup data source"](https://one.newrelic.com/marketplace/install-data-source) tells us to now use `node --experimental-loader newrelic/esm-loader.mjs -r newrelic your-program.js` when starting apps. Unfortunately this is not possible with ts-node. Neither `--loader` nor `--experimental-loader` are available as command line options in ts-node.

as an alternative, i gave this a shot, which seemed hopeful

```
NODE_OPTIONS='--experimental-loader=newrelic/esm-loader.mjs' NODE_ENV=${NODE_ENV:-development} npx ts-node -r tsconfig-paths/register -r newrelic ./src/index.ts
(node:33379) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("newrelic/esm-loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:33421) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("newrelic/esm-loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/aronlilland/Documents/dev/steppingStonesInternational/pathway-api/src/index.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:143:22)
    at async nextLoad (node:internal/modules/esm/hooks:865:22)
    at async nextLoad (node:internal/modules/esm/hooks:865:22)
    at async Hooks.load (node:internal/modules/esm/hooks:448:20)
    at async handleMessage (node:internal/modules/esm/worker:196:18) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

i then tried the same command with nodemon (in dev mode)
```
NODE_OPTIONS='--experimental-loader=newrelic/esm-loader.mjs' NODE_ENV=${NODE_ENV:-development} nodemon -r tsconfig-paths/register -r newrelic ./src/index.ts
(node:34580) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("newrelic/esm-loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node -r tsconfig-paths/register -r newrelic ./src/index.ts`
(node:34614) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("newrelic/esm-loader.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/aronlilland/Documents/dev/steppingStonesInternational/pathway-api/src/index.ts
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:160:9)
    at defaultGetFormat (node:internal/modules/esm/get_format:203:36)
    at defaultLoad (node:internal/modules/esm/load:143:22)
    at async nextLoad (node:internal/modules/esm/hooks:865:22)
    at async nextLoad (node:internal/modules/esm/hooks:865:22)
    at async Hooks.load (node:internal/modules/esm/hooks:448:20)
    at async handleMessage (node:internal/modules/esm/worker:196:18) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```
this recommended moving command line arguments to a file and to use `register()`

so I tried moving the loader commands to a register file at the root of my app and called it `register.js`
```javascript
import { register } from 'node:module'
import { pathToFileURL } from 'node:url'

register('newrelic/esm-loader.mjs', pathToFileURL('./'))
```

I then modified the bootup script
`NODE_OPTIONS='--import=./register.mjs' NODE_ENV=${NODE_ENV:-development} nodemon -r ts-node/register -r tsconfig-paths/register -r newrelic ./src/index.ts`

but this too failed, I am pretty much stuck.

## Your Environment
`node@20.11.1`
`npm@10.5.0`
`ts-node@10.9.2`

using volta for node version management
OS: MacOS 14.4.1 (sonoma) with 2.4 GHz 8-Core Intel Core i9

**Comment by bizob2828** [comment]
@alilland you may want to ask the ts-node folks. `--loader` or `--experimental-loader` are Node.js runtime CLI args.  have you tried 

`NODE_OPTIONS='--loader newrelic/esm-loader.mjs -r newrelic`?

**Comment by bizob2828** [comment]
I'm going to close this issue as it appears to be interoperability with ts-node.
