### ISSUE TITLE
Application occasionally crashes with grpc error of "14 UNAVAILABLE: The service is temporarily unavailable. Please retry with exponential backoff." error

### ISSUE THREAD

**Issue by TraGicCode** [newrelic/node-newrelic#2143]
## Description

Our GraphQL node application using express is crashing due to an exception being thrown by the newrelic agent. Below is log of the error and stack trace thrown by the newrelic agent. Any help is greatly appreciated as we would love to prevent this from happening!

NewRelic Support Case Number:
Case #00197682

## Expected Behavior

The application would not crash due to the newrelic node agent

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

```
{
  "application": "<REDACTED>",
  "date": "Fri Apr 12 2024 14:36:07 GMT+0000 (Coordinated Universal Time)",
  "entity.guid": "NTE5ODk5fEFQTXxBUFBMSUNBVElPTnwxMTMwNzgwODE2",
  "entity.guids": "NTE5ODk5fEFQTXxBUFBMSUNBVElPTnwxMTMwNzgwODE2",
  "entity.name": "<REDACTED>(prod)",
  "entity.type": "SERVICE",
  "error.class": "Error",
  "error.code": 14,
  "error.details": "The service is temporarily unavailable. Please retry with exponential backoff.",
  "error.message": "14 UNAVAILABLE: The service is temporarily unavailable. Please retry with exponential backoff.",
  "error.note": "Exception occurred in retry method that was not classified as transient",
  "error.stack": "Error: 14 UNAVAILABLE: The service is temporarily unavailable. Please retry with exponential backoff.\n    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:179:52)\n    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)\n    at onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)\n    at runInContextCb (/app/node_modules/newrelic/lib/shim/shim.js:1168:22)\n    at AsyncLocalStorage.run (node:async_hooks:330:14)\n    at AsyncLocalContextManager.runInContext (/app/node_modules/newrelic/lib/context-manager/async-local-context-manager.js:65:36)\n    at Shim.applySegment (/app/node_modules/newrelic/lib/shim/shim.js:1158:25)\n    at wrapper (/app/node_modules/newrelic/lib/shim/shim.js:1760:17)\n    at Object.nrListener.onReceiveStatus (/app/node_modules/newrelic/lib/instrumentation/grpc-js/grpc.js:110:11)\nCaused by:...",
  "exception": true,
  "hostname": "<REDACTED>-5c7687d9dd-5n87d",
  "level": "error",
  "message": "uncaughtException: 14 UNAVAILABLE: The service is temporarily unavailable. Please retry with exponential backoff.\nError: 14 UNAVAILABLE: The service is temporarily unavailable. Please retry with exponential backoff.\n    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:179:52)\n    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)\n    at onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)\n    at runInContextCb (/app/node_modules/newrelic/lib/shim/shim.js:1168:22)\n    at AsyncLocalStorage.run (node:async_hooks:330:14)\n    at AsyncLocalContextManager.runInContext (/app/node_modules/newrelic/lib/context-manager/async-local-context-manager.js:65:36)\n    at Shim.applySegment (/app/node_modules/newrelic/lib/shim/shim.js:1158:25)\n    at wrapper (/app/node_modules/newrelic/lib/shim/shim.js:1760:17)\n    at Ob...",
  "newrelic.logPattern": "nr.DID_NOT_MATCH",
  "newrelic.source": "logs.APM",
  "os.loadavg": "[0.22,0.32,0.39]",
  "os.uptime": 1672326.04,
  "process.argv": "[\"/usr/local/bin/node\",\"/app/index.js\"]",
  "process.cwd": "/app",
  "process.execPath": "/usr/local/bin/node",
  "process.gid": 0,
  "process.memoryUsage.arrayBuffers": 2066101,
  "process.memoryUsage.external": 6475208,
  "process.memoryUsage.heapTotal": 295112704,
  "process.memoryUsage.heapUsed": 179712288,
  "process.memoryUsage.rss": 366444544,
  "process.pid": 1,
  "process.uid": 0,
  "process.version": "v16.20.2",
  "timestamp": 1712932567071
}
```

## Steps to Reproduce

We do not know how to reproduce this as it just happens after the application has been running for a while.

## Your Environment

Node Version:
16.20.2

```
    "@babel/runtime": "^7.4.2",
    "@google-cloud/storage": "^2.4.3",
    "@graphql-tools/schema": "^8.3.10",
    "@newrelic/apollo-server-plugin": "^4.0.0",
    "apollo-server-core": "^3.13.0",
    "apollo-server-errors": "^3.3.1",
    "apollo-server-express": "^3.13.0",
    "await-to-js": "^2.1.1",
    "axios": "^0.18.0",
    "base64-stream": "^1.0.0",
    "body-parser": "^1.18.3",
    "date-fns": "^2.16.1",
    "express": "^4.19.2",
    "firebase-admin": "^8.13.0",
    "flat": "^5.0.2",
    "graphql": "^16.8.1",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.11",
    "moment": "^2.29.1",
    "newrelic": "^11.14.0",
    "passport": "^0.4.0",
    "passport-http": "^0.3.0",
    "qs": "^6.7.0",
    "sort-keys": "^2.0.0",
    "uuid": "^8.3.1",
    "winston": "^3.13.0",
    "yargs": "^13.2.2"
```

Looking into the node_modules folder of the newrelic agent npm package, it looks like it's using this version of grpc
```
  "name": "@grpc/grpc-js",
  "version": "1.10.4",
```

## Additional context

We are running graphql with expressjs. We also have the @newrelic/apollo-server-plugin installed.

**Comment by bizob2828** [comment]
@TraGicCode I'm unclear what you're reporting.  Your example is log json that is showing you have an error in your grpc server not the node agent.  We are in the stack trace but that's because we instrument grpc servers.  I see you have opened a support case.  I recommend going that route to get assistance.  Unless you can provide a reproduction case but at this time it just appears like a grpc error.

**Comment by TraGicCode** [comment]
> @TraGicCode I'm unclear what you're reporting. Your example is log json that is showing you have an error in your grpc server not the node agent. We are in the stack trace but that's because we instrument grpc servers. I see you have opened a support case. I recommend going that route to get assistance. Unless you can provide a reproduction case but at this time it just appears like a grpc error.

Hey,

I noticed that newrelic had a dependency on this so i was guessing it was newrelic having issues communicating log/apm data back to newrelics servers.  The only other dependency that uses this would be firebase-admin.  Our applications uses this library to talk to google firestore for it's database.

Also, our application is not a grpc server but is simply a node.js application that uses express.js to host graphql.

**Comment by bizob2828** [comment]
gRPC is only used if you have infinite tracing enabled.

**Comment by TraGicCode** [comment]
hey @bizob2828 ,

Feel free to close this ticket if you fill this is not an issue with the newrelic-agent.  In the mean time, i plan on updating our firestore js library to see if this makes things better
