### ISSUE TITLE
Update agent to handle updates from `import-in-the-middle@1.11.1`

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-newrelic#2617]
### Description
It looks like this [PR](https://github.com/nodejs/import-in-the-middle/pull/153/files), broke our `wrapReturn` shim function which wraps an export in a Proxy. After updating to `import-in-the-middle@1.11.1` you get 

```sh
TypeError: getters.get(...)[name] is not a function
    at Object.get (register.js:20:37)
    at Object.set (shimmer.js:648:30)
    at DatastoreShim.wrapEachProperty (shim.js:347:20)
    at Array.forEach (<anonymous>)
    at DatastoreShim.wrap (shim.js:334:14)
    at DatastoreShim.wrapReturn (shim.js:398:15)
    at instrumentPGNative (pg.js:61:10)
    at initialize (pg.js:33:12)
    at _firstPartyInstrumentation (shimmer.js:711:29)
    at loadInstrumentation (shimmer.js:675:25)
```

It's failing when we try to assign the exported module property as wrapped [here](https://github.com/newrelic/node-newrelic/blob/main/lib/shim/shim.js#L347)

### Steps to Reproduce

1. `npm i import-in-the-middle@latest`
2. `npm run versioned:internal:major pg-esm`

### Expected Result
Tests pass

### Actual Result
Tests fail

**Comment by bizob2828** [comment]
This [PR](https://github.com/nodejs/import-in-the-middle/pull/155) fixes the issue
