### ISSUE TITLE
New Relic transaction throwing error when apollo tries to send multiple queries

### ISSUE THREAD

**Issue by doudou1212** [newrelic/node-newrelic#296]
I try to send a query
```
{
  posts(
    app_name:"xxx",
    section_name: "xxx",
    user_type: "xx"
  )
  {
    posts {
      title
      fields{
        video{
            mediaInfo
        }
      }
    }
  }
}
```
In above query, when getting `mediaInfo` in Video, it will send another request to get media info. 
So actually the above query will send two requests:
1. get post
2. get mediaInfo

While I got a error:

```
 this._segment && this._segment.probe('Segment removed from tracer')
                                   ^

TypeError: this._segment.probe is not a function
    at Tracer.segmentSetter (/path/node_modules/newrelic/lib/transaction/tracer/index.js:46:36)
    at Shim.setActiveSegment (/path/node_modules/newrelic/lib/shim/shim.js:1311:30)
    at process.wrappedFatalException [as _fatalException] (/path/node_modules/newrelic/lib/instrumentation/core/globals.js:21:14)
```

newrelic version: 5.7.0
apollo-server-express version: 2.8.1
graphql version: 14.2.1
node version: 10.15.3

**Comment by doudou1212** [comment]
we resolved this issue
