### ISSUE TITLE
Prioritize prebuilt binaries when installing.

### ISSUE THREAD

**Issue by nwsparks** [newrelic/node-newrelic#327]
From reading this issue, https://github.com/newrelic/node-native-metrics/issues/62, it appears that the default behavior of installing the New Relic Agent is to attempt it with Gyp first and then fall back to pre-built binaries.

It would be nice if this reliance on Gyp could be removed, or the pre-built binaries were tried first when installing so that the build logs are not full of errors. It's pretty common these days to use minimal containers that wouldn't have Python, Make, etc installed and it is frustrating seeing these errors in the logs every time we build.

`npm install --quiet newrelic`

```
> @newrelic/native-metrics@5.0.0 install /node/node_modules/@newrelic/native-metrics
> node ./lib/pre-build.js install native_metrics

============================================================================
Attempting install in native-metrics module. Please note that this is an
OPTIONAL dependency, and any resultant errors in this process will not
affect the general performance of the New Relic agent, but event loop and
garbage collection metrics will not be collected.
============================================================================

> /usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean configure
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:314:5)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:81:21)
gyp ERR! System Linux 4.19.76-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean" "configure"
gyp ERR! cwd /node/node_modules/@newrelic/native-metrics
gyp ERR! node -v v12.15.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
install successful: _newrelic_native_metrics-5_0_0-native_metrics-72-linux-x64
```

**Comment by jdfm** [comment]
There are environment variables that can be used before trying to install the package that will just skip the build step.

`NR_NATIVE_METRICS_NO_BUILD` specifically: https://github.com/newrelic/node-native-metrics#installation

**Comment by nwsparks** [comment]
@jdfm thanks! just tested this and can confirm it gets rid of the gyp errors.

**Comment by blackmad** [comment]
I'm also wondering about this - why not try downloading first? that's what node-gyp-pre does and what seems to generally be faster and easier.

I understand about NR_NATIVE_METRICS_NO_DOWNLOAD but I'd prefer if it instead was _PREFER_DOWNLOAD so it tried to do the fast/easy/prebuilt case first and falls back to compiling.

**Comment by nwsparks** [comment]
@blackmad yah I definitely agree with that.
