### ISSUE TITLE
Tracer not Set on Shim: Cannot read property 'getSegment' of undefined

### ISSUE THREAD

**Issue by astormnewrelic** [newrelic/node-newrelic#455]
## Description

We've had a report of agents (agent version 5.8.0) crashing with the following error.

    /usr/src/app/node_modules/newrelic/lib/shim/shim.js:1269
    return this.tracer.getSegment()
    ^
    TypeError: Cannot read property 'getSegment' of undefined
    at Shim.getSegment (/usr/src/app/node_modules/newrelic/lib/shim/shim.js:1269:22)
    at Shim.getActiveSegment (/usr/src/app/node_modules/newrelic/lib/shim/shim.js:1291:22)
    at process.wrappedProcess [as nextTick] (/usr/src/app/node_modules/newrelic/lib/instrumentation/core/timers.js:13:30)
    at exports.MongoDB.MongoDB.log (/usr/src/app/node_modules/winston-mongodb/lib/winston-mongodb.js:242:11)
    at exports.MongoDB.Transport.logException (/usr/src/app/node_modules/winston/lib/winston/transports/transport.js:134:8)
    at logAndWait (/usr/src/app/node_modules/winston/lib/winston/logger.js:646:15)
    at /usr/src/app/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/usr/src/app/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/usr/src/app/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at exports.Logger.Logger._uncaughtException (/usr/src/app/node_modules/winston/lib/winston/logger.js:669:9)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at process.wrappedEmit [as emit] (/usr/src/app/node_modules/newrelic/lib/instrumentation/core/globals.js:58:23)
    at process._fatalException (bootstrap_node.js:378:26)
    at process.wrappedFatalException [as _fatalException] (/usr/src/app/node_modules/newrelic/lib/instrumentation/core/globals.js:35:23) 
    
Is appears that during a routine handling of a fatal exception, that a shim's tracer property is unset/undefined, and that leads to this fatal error.  

While this is happening in an older agent version, because we can't get to a root cause there's concerns in may impact current versions of the agent as well. 

Step one will be reproducing this crasher.  Once it's reproduced and we understand it better, we can decide on the long (or short) term fix.      

## Expected Behavior

Agent doesn't crash, and allows the fatal exception to do whatever it was going to do. 

## Steps to Reproduce

Can't yet.

## Your Environment

Node 8.x
Agent version 5.8

**Comment by astormnewrelic** [comment]
datapoint: tried putting together a basic reproduction that mimics the async and event calling patterns on display in that callstack

    const newrelic = require('newrelic')
    const express = require('express')
    const app = express()

    app.get('/hello', (req, res, next) => {

      // 1. async hop to get out of express and have this
      // be uncaught and crash the application
      setTimeout(() => {
        const foobar = {}
        // 2. this will be a fatal error, triggering the uncaughtException
        foobar.foo.bar++
      }, 10)

      res.send("Hello World")
      res.end()
    })

    process.on('uncaughtException', function (err) {
      // 3. listener for uncaughtException called

      // simulating async hop that async library makes
      setTimeout(() => {
        // 5. scheduling some work on process.nextTick, similar to what's
        //    happening in the mongo logger
        
        process.nextTick(() => {
          // 6. if this reproduces, we'd expect that we've never
          // reach this point as the wrapper in process.nextTick
          // would crash out
          console.log('got to nextTick, things did not crash')
        })
      }, 10)
    })

    app.listen(9111)

No crash -- so we're definitely looking at a bad interaction between two libraries.  Also worth noting that `domains` might be in play, further complicating things.

**Comment by rr0214** [comment]
We are trying to solve this more holistically with our ASYNC tracking work
