### ISSUE TITLE
NewRelic crashing the entire process

### ISSUE THREAD

**Issue by maciek-ibm** [newrelic/node-newrelic#467]
It seems that when our frontend is connecting with the backend and when we are throwing an error it crashes the whole process on the server forcing us to manually restart the application on the server.

[ERROR ][Aug 21, 2020, 08:07:36 AM UTC] error proxing to backend /attachment/download/c7b53030-e384-11ea-8758-d1b9f3dfdf54 | Error: read ECONNRESET
/opt/mssdev/xfrtest/node_modules/newrelic/lib/shim/shim.js:1436
throw error // Rethrowing application error, this is not an agent error.
^Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
at ServerResponse.setHeader (_http_outgoing.js:470:11)
at ServerResponse.header (/opt/mssdev/xfrtest/node_modules/express/lib/response.js:767:10)
at ServerResponse.send (/opt/mssdev/xfrtest/node_modules/express/lib/response.js:170:12)
at ServerResponse.json (/opt/mssdev/xfrtest/node_modules/express/lib/response.js:267:15)
at ServerResponse.send (/opt/mssdev/xfrtest/node_modules/express/lib/response.js:158:21)
at /opt/mssdev/xfrtest/dist/server/server.js:230:21
at ClientRequest.proxyError (/opt/mssdev/xfrtest/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:163:11)
at ClientRequest.emit (events.js:198:13)
at ClientRequest.wrapped (/opt/mssdev/xfrtest/node_modules/newrelic/lib/transaction/tracer/index.js:198:22)
at ClientRequest.wrappedRequestEmit (/opt/mssdev/xfrtest/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:160:26)
at TLSSocket.socketErrorListener (_http_client.js:401:9)
at TLSSocket.emit (events.js:198:13)
at Shim.applySegment (/opt/mssdev/xfrtest/node_modules/newrelic/lib/shim/shim.js:1430:20)
at TLSSocket.wrapper [as emit] (/opt/mssdev/xfrtest/node_modules/newrelic/lib/shim/shim.js:2092:17)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at Shim.applySegment (/opt/mssdev/xfrtest/node_modules/newrelic/lib/shim/shim.js:1430:20)
at wrapper (/opt/mssdev/xfrtest/node_modules/newrelic/lib/shim/shim.js:2092:17)
at process._tickCallback (internal/process/next_tick.js:63:19)
Logging to /opt/rp/log/xfrtest.log

**Comment by astormnewrelic** [comment]
Closing this out in favor of the the internal support ticket.  Don't hesitate to reopen if you have more information or need more help.
